pipeline {
    agent any
    parameters {
        string(name: 'CM_HOST', defaultValue: 'http://cloudera-manager:7180', description: 'Cloudera Manager Host')
        string(name: 'USERNAME', defaultValue: 'admin', description: 'Cloudera Manager Username')
        string(name: 'PASSWORD', defaultValue: 'admin', description: 'Cloudera Manager Password')
        string(name: 'CLUSTER_NAME', defaultValue: 'my-cluster', description: 'Cluster Name')
        string(name: 'VERSION', defaultValue: '7.2.1', description: 'CDH Version')
        string(name: 'HOSTS', defaultValue: 'host1 host2 host3', description: 'Space-separated list of hostnames to add')
        string(name: 'PRODUCT', defaultValue: 'CDH', description: 'Product Name')
    }
    stages {
        stage('Deploy Cloudera Cluster') {
            steps {
                script {
                    def hostsList = params.HOSTS.split()
                    sh "python3 cloudera_deployment/main.py --cm_host ${params.CM_HOST} --username ${params.USERNAME} --password ${params.PASSWORD} --cluster_name ${params.CLUSTER_NAME} --version ${params.VERSION} --hosts ${hostsList.join(' ')} --product ${params.PRODUCT}"
                }
            }
        }
    }
}

